name: Build Android APK

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          openjdk-17-jdk \
          zip \
          unzip \
          automake \
          libtool \
          pkg-config \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \
          cmake \
          libffi-dev \
          libssl-dev \
          autoconf \
          libltdl-dev
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython==0.29.33 pillow
    
    - name: Create assets
      run: |
        mkdir -p assets
        # Create icon if not exists
        if [ ! -f assets/icon.png ]; then
          python -c "
from PIL import Image, ImageDraw
img = Image.new('RGBA', (512, 512), (26, 95, 122, 255))
draw = ImageDraw.Draw(img)
draw.ellipse([150, 150, 362, 362], fill=(45, 106, 79, 255))
draw.text((180, 230), 'EN', fill=(255, 255, 255, 255))
img.save('assets/icon.png')
          "
        fi
        # Create splash if not exists
        if [ ! -f assets/splash.png ]; then
          python -c "
from PIL import Image, ImageDraw
img = Image.new('RGBA', (1080, 1920), (14, 17, 23, 255))
draw = ImageDraw.Draw(img)
draw.rectangle([340, 700, 740, 1100], fill=(26, 95, 122, 255))
draw.text((380, 850), 'ELITE', fill=(255, 255, 255, 255))
draw.text((350, 920), 'NEURAL', fill=(255, 193, 7, 255))
img.save('assets/splash.png')
          "
        fi
    
    - name: Build APK with Buildozer
      run: |
        buildozer android debug
    
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: elite-neural-apk
        path: bin/*.apk
        retention-days: 30
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: bin/*.apk
        body: |
          ## Elite Neural Evolve v8.0.0
          
          ### 📱 Application Android Native
          
          **Installation:**
          1. Téléchargez l'APK
          2. Autorisez les sources inconnues
          3. Installez l'application
          
          **Fonctionnalités:**
          - 🧠 IA prédictive auto-apprenante
          - 💰 Bankroll management complet
          - 📊 Statistiques détaillées
          - 🔗 API Football connectée
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
